### ISSUE TITLE
concurrent modification bug

### ISSUE THREAD

**Issue by igorbernstein2** [dangermike/gobigtableperf#1]
Hi,

I think there is a bug in the `concurrency` command:
https://github.com/dangermike/gobigtableperf/blob/5507d80835176f8c6a99fc820d368bcb71a8dda6/main.go#L277:

```mykeys := keys[:]```
Creates a copy of the slice, but still shares the underlying array storage. Which creates a race condition in the shuffle here:
https://github.com/dangermike/gobigtableperf/blob/5507d80835176f8c6a99fc820d368bcb71a8dda6/main.go#L279
Which will shuffle the underlying array

**Comment by dangermike** [comment]
Thanks for the catch! I'm surprised I didn't see the problem more often.

**Comment by dangermike** [comment]
Fixed in commit 52f06eb
